DROP TABLE IF EXISTS curtida CASCADE;
DROP TABLE IF EXISTS comentario CASCADE;
DROP TABLE IF EXISTS postagem CASCADE;
DROP TABLE IF EXISTS amizade CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;

CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_completo VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    apelido VARCHAR(50),
    data_nascimento DATE NOT NULL,
    senha VARCHAR(128) NOT NULL,
    imagem_perfil VARCHAR(512),
estadio VARCHAR(255) NOT NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (id),
    CONSTRAINT uk_usuario_email UNIQUE (email)
);


CREATE TABLE postagem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_id BIGINT NOT NULL,
    conteudo TEXT NOT NULL,
    data_postagem TIMESTAMP NOT NULL,
    publico BOOLEAN NOT NULL,
    CONSTRAINT pk_postagem PRIMARY KEY (id),
    CONSTRAINT fk_postagem_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

CREATE TABLE amizade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    solicitante_id BIGINT NOT NULL,
    solicitado_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT pk_amizade PRIMARY KEY (id),
    CONSTRAINT uk_amizade_solicitacao UNIQUE (solicitante_id, solicitado_id),
    CONSTRAINT fk_amizade_solicitante FOREIGN KEY (solicitante_id) REFERENCES usuario(id),
    CONSTRAINT fk_amizade_solicitado FOREIGN KEY (solicitado_id) REFERENCES usuario(id)
);


CREATE TABLE curtida (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    postagem_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    CONSTRAINT pk_curtida PRIMARY KEY (id),
    CONSTRAINT uk_curtida_unica UNIQUE (postagem_id, usuario_id),
    CONSTRAINT fk_curtida_postagem FOREIGN KEY (postagem_id) REFERENCES postagem(id),
    CONSTRAINT fk_curtida_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

CREATE TABLE comentario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    postagem_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    conteudo TEXT NOT NULL,
    data_comentario TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_comentario PRIMARY KEY (id),
    CONSTRAINT fk_comentario_postagem FOREIGN KEY (postagem_id) REFERENCES postagem(id),
    CONSTRAINT fk_comentario_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);